- name : user
  hosts: user
  become: yes
  tasks:
  - name: node js disable existing 
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: node js 18 install
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create user
    ansible.builtin.user:
      name: roboshop

  - name: recursively remove directory
    ansible.builtin.file:
      name: /app
      state: absent

  - name: remove any app directory 
    ansible.builtin.file:
      name: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: copy user related files
    ansible.builtin.get_url:
      url:  https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: unzip
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install npm
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: systemd changes user service
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemd reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: mongod repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: mongod installation
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.roboshop.store --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{user_count}}"

  - name: load user data
    ansible.builtin.command: mongo --host mongodb.roboshop.store < /app/schema/user.js
    when: user_count.stdout == "0" # keep double quotes

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes